### ISSUE TITLE
JAX backend

### ISSUE THREAD

**Issue by joaogui1** [google-research/evoflow#68]
Do you plan to have a JAX backend? Is it feasible? Would you accept a PR implementing one?

**Comment by ebursztein** [comment]
Hey,

Yes it is doable and probably quite easy to add basic support thanks to the backend abstraction. I am considering it for a few days since a few jax team member reached out :) 

I was not super excited about the fact that it didn't work on Windows but with WSL2 that should go away (I need to double check today now that I installed it)

Early test with JAX show that support for tensor update (which make the TF backend unsuable) works quite well for the evoflow use-cases: https://colab.research.google.com/drive/1eoG3IY-qSn7YaS2S_rBZIraupWCZp2fm so I expect it to be significantly  faster than TF until slicing is resolved in TF.ops.

The reason, I didn't started is that the way umap and vmap works is fundamentally different than tensorflow distribution strategy so supporting both is going to "interesting"  for  distributed GPU and TPU. 

I will start writing basic support for it today to see how hard it is.

**Comment by joaogui1** [comment]
I'm happy to help if you need it

**Comment by ebursztein** [comment]
I created a branch: https://github.com/google-research/evoflow/tree/jax you can try it. It implement the basic support but there are issue with some of the backend primitives. I fixed the obvious ones, now the remaining ones need more careful analysis. I know how to fix the update one, the other feel free to look at it.

To test the ops: pytest-3  tests/ops/
To test evoflow with Jax :  pytest-3 --backend=jax tests/
